name: Pipeline

on:
  push:
    paths:
      - 'trigger.txt'

jobs:
  vm:
    uses: ./.github/workflows/vm.yml
    secrets: inherit

  storage:
    uses: ./.github/workflows/storage.yml
    secrets: inherit